In [1]:
import numpy as np

In [4]:
myarr=np.array([2,3,4,5],np.int8)

In [5]:
myarr

array([2, 3, 4, 5], dtype=int8)

In [6]:
myarr[0]

2

In [7]:
myarr.shape

(4,)

In [8]:
myarr.dtype

dtype('int8')

In [17]:
arr=np.array([[1,2,3],[4,5,6]])

In [18]:
arr[0][1]

2

In [19]:
arr[0][1]=7

In [20]:
arr[0][1]

7

In [21]:
arr

array([[1, 7, 3],
       [4, 5, 6]])

In [23]:
zeros_arr=np.zeros((3,5))

In [24]:
zeros_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
rng=np.arange(10)

In [26]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
lspace=np.linspace(1,5,12)

In [29]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [30]:
emp=np.empty((4,6))

In [31]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511018e-306, 1.06811354e-306, 7.56599807e-307],
       [8.90104239e-307, 1.24610383e-306, 1.69118108e-306,
        8.06632139e-308, 1.20160711e-306, 1.69119330e-306],
       [1.02360663e-306, 1.69119330e-306, 8.45605478e-307,
        6.89804133e-307, 8.90104239e-307, 1.42417221e-306],
       [7.56597770e-307, 1.02360867e-306, 1.51318739e-306,
        9.34608432e-307, 1.78020848e-306, 2.22522596e-306]])

In [32]:
ide=np.identity(10)

In [33]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [35]:
arr=np.arange(10)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
arr=arr.ravel()

In [40]:
arr.shape

(10,)

In [41]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [42]:
arr=np.array(x)

In [43]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
arr.sum(axis=0)

array([12,  8,  9])

In [45]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [46]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [50]:
arr.flat

In [51]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [53]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [54]:
arr.ndim

2

In [55]:
arr.size

9

In [56]:
arr.nbytes

36

In [57]:
arr.argmax()

6

In [58]:
one=np.array([1,2,5])

In [59]:
one.argmax()

2

In [60]:
one.argmin()

0

In [61]:
one.argsort()

array([0, 1, 2], dtype=int64)

In [63]:
arr.argmin()

8

In [64]:
arr.argmax()

6

In [67]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [65]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [66]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [68]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [69]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
arr2=np.array([[1,1,2],[2,1,0],[1,0,1]])

In [71]:
arr2

array([[1, 1, 2],
       [2, 1, 0],
       [1, 0, 1]])

In [72]:
arr+arr2

array([[2, 3, 5],
       [6, 6, 6],
       [8, 1, 1]])

In [73]:
arr*arr2

array([[1, 2, 6],
       [8, 5, 0],
       [7, 0, 0]])

In [74]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [75]:
arr.sum()

29

In [76]:
arr.max()

7

In [77]:
arr.min()

0

In [78]:
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [80]:
np.count_nonzero(arr)

8

In [81]:
import sys

In [82]:
l=[1,2,3]

In [84]:
arr=np.array([1,2,3])

In [85]:
sys.getsizeof(1)*len(l)

84

In [88]:
arr.itemsize*arr.size

12